### ISSUE TITLE
Integrate with TeamSpeak server

### ISSUE THREAD

**Issue by mfreiholz** [mfreiholz/ocs#10]
The video server currently doesn't know anything about TeamSpeak. It could be possible to connect via the TeamSpeak's query console and read current status information from there.

This could also make it possible to store configurations for the VideoServer somewhere in TeamSpeak's VirtualServer config.

**Comment by Spazmic** [comment]
+ ts3video can be only used by particular servergroups?

**Comment by mfreiholz** [comment]
If the TS3-query-console provides group-membership information, it should be possible.

**Comment by mfreiholz** [comment]
It's possible to define a list of TS3 server groups, which are allowed to use the video-conference feature.

New config section:
```ini
[teamspeak3-serverquery-bridge]
# Enables the bridge to TeamSpeak 3.
# @version 0.4
enabled=1

# Address of the TeamSpeak server.
# It usually runs on the same host (127.0.0.1)
# @version 0.4
address=127.0.0.1

# The port of the TeamSpeak server query-console.
# @version 0.4
port=10011

# Login information for the query-console.
# @version 0.4
loginname=serveradmin
loginpassword=

# The connection will change the visible nickname of the query-console user.
# @version 0.4
# @note Do not use! Leave it empty for now! Or at least not more than 10 characters!
nickname=OCS

# Port of the virtual server used for authorization.
# @version 0.4
virtualserverport=9987

# Comma separated list of server group IDs (sgid),
# which are allowed to use the video server.
# Leave empty to allow all groups.
allowedservergroups=
```
