### ISSUE TITLE
local hosting problem

### ISSUE THREAD

**Issue by sog23** [mfreiholz/ocs#20]
im hosting my ts3-server on my lan.
if i want to connect in the same room as 3 other members who connected to my server they cant see me, im alone in the room. they can see each other.
im connecting via lan to the ts3 & ts3video.

this was working in 0.2
maybe a nat-loopback problem?

**Comment by mfreiholz** [comment]
The important thing is, that all users need to connect to the same Teamspeak 3 IP. If you are using 127.0.0.1 as the IP to connect to your TeamSpeak server, try to use your external IP address instead.

The IP address of the TeamSpeak server is used to generate a unique conference-id on the VideoServer.

**Comment by sog23** [comment]
my server is on 192.168.1.105 and me 101 :/
i cannot on my external ip on my server, just via lan :(

**Comment by mfreiholz** [comment]
Does that mean, that all other users use the same IP address to connect on the TS server (192.168.1.105)?

**Comment by sog23** [comment]
yes the 105 is the lan server, but the conenct trough the external internet ip adress

**Comment by mfreiholz** [comment]
And why can't you connect with the external IP address?
It is the only possible way to join the same video conference.

**Comment by sog23** [comment]
okay stop... as u said "generate a unique conference-id"
if everyone uses the same id it works.. if i use the default settings its my lanip/port#chanid its not working.. if everyone use the same id e.g only "612" (channelnumber) it works.

so its solved for me, thanks :)
