### ISSUE TITLE
Disable "Received your poke!" message

### ISSUE THREAD

**Issue by ToFran** [mfreiholz/ocs#27]
If you have the plugin installed/enabled, when someone pokes you, you automatically reply with a message:  "*<USENAME>: Received your poke!*"
This is the behaviour of the **Test Plugin** and should not be implemented in this plugin, the main reason is that it resets your idle time every time you get poked.
Please disable this.

**Comment by mfreiholz** [comment]
Fixed with release 0.4. Please download the latest version (but the version needs the update, too).

**Comment by ToFran** [comment]
Oh sorry, I was not using the latest version, thank you.
