### ISSUE TITLE
Logging location missing

### ISSUE THREAD

**Issue by Jonas-Degn** [mfreiholz/ocs#30]
According to the documentation the log is located in $TEMP/ts3video-server.log.

The WORKDIR is defined in start-initd.sh but I don't see in this file or in the documentation where this $TEMP location should be.
I've also run a ``` find / -name "ts3video-server.log" ``` which makes me wonder if the file even exists.

**Comment by mfreiholz** [comment]
Hi Jonas-Degn,
the newest version (v0.5) logs to `$TEMP/serverapp.log` by default. I forgot to update the documentation.

It is also possible to configure the log location in your server's `default.ini`file:

```ini
# Settings about logging.
#
# Some available variables for paths:
#   $TEMPDIR = Path to temporary directory of the running user.
#   $APPDIR = Path to directory of the application (e.g. C:\Program Files\App)
#
# @version 0.5
[logging]
# Path to log output file.
# @version 0.5
FilePath=$TEMPDIR/serverapp.log

# Path to logging framework configuration file.
# @version 0.5
ConfigFilePath=$APPDIR/logging.conf

# If "1", the application will also log to console STDOUT (requires: --console).
# @version 0.5
ConsoleAppenderEnabled=0
```
