### ISSUE TITLE
Error, white screen square instead of the Video stream

### ISSUE THREAD

**Issue by mjadrake** [mfreiholz/ocs#31]
Im in a teamspeak channel that sells stream videos, so as I was told, I had to installed the TS3Video Plugin and so I did it step by step, but each time I try to see the stream, it only appears a white screen square instead of the Video stream, as seen on the image below.

http://imgur.com/ML7y6vG

Is only my problem since all the guys that are in this channel can see the video.

And the strange is, that some months ago I also could see it without any problems, but than I had to format my PC and since that I was never able to see this streams anymore. 

Is there any way of fixing this? Am I missing any other program that allows me to see this streams?

Since I format my PC, I only installed the basics programs to work and operate. So its possible Im missing some trivial program or update that everyone hads but I dont.

Im using Windows7.

Please help me out, since this streams are very important for my work, and I really need this working out well.

Thanks in advance ;)

**Comment by mfreiholz** [comment]
Hi Drake,
hm you are now the 2nd person i know of who got this problem.

I really have no idea whats the problem, especially since i can't reproduce it.

The next release (which i hope to release this week), will have an option to turn hardware acceleration off (but costs more CPU power).

**Comment by mfreiholz** [comment]
Can you give me some detailed information about your hardware, please?

**Comment by mjadrake** [comment]
Thanks for the quick response

Here is:
http://imgur.com/RW85X1w

I'm a bit noob, so please let me know if this what your looking for or if you need any other info. 

Thanks ;)

**Comment by mfreiholz** [comment]
Do you have a dedicated Graphics-Card? NVIDIA... ATI/AMD?
You can see it in "Device Manager" (e.g.: https://mfreiholz.de/share/2016-01/qGUnJxMB5LETxojcwiXuXF69WpaD8aAv.png)

**Comment by mjadrake** [comment]
Here it is:
http://imgur.com/WWdpoHx

But the strange thing about this problem is that this plugin allready work in this computer. But when I had to format this PC, about 2 months ago, and I tried to see the streams, than this error occurs.

So this is why i thought it was a software problem not a hardware problem. But as I said, Im a complete noob about this questions :)

**Comment by mfreiholz** [comment]
I'm think it's some missing DLL from OpenGL or DirectX. MAybe you previously had it installed, because of a game or some other software.

You could try to install DirectX SDK from Microsoft..  - sorry no other idea right now :-/

**Comment by mjadrake** [comment]
Ok, I´ll try it out, and then test it with their streams. I let you know if it worked.

Thanks a lot for the help. ;)

**Comment by mfreiholz** [comment]
It might also work to install the latest graphics cards driver from http://www.amd.com/

I think this is the one you need:
http://support.amd.com/en-us/download/desktop/legacy?product=legacy2&os=Windows%207%20-%2064

**Comment by mjadrake** [comment]
Thanks, I´ll try that too. ;)

**Comment by mjadrake** [comment]
Problem solved, thanks a lot for the help. ;)
