### ISSUE TITLE
Any DLL not found - TS3VIDEO Version 0.6

### ISSUE THREAD

**Issue by Schizzo91** [mfreiholz/ocs#33]
After istall, my pc gets an error:
Unable to start the program, VCRUNTIME140.dll not found.

I have Windows 7, 
a my friend have Windows 8 and he doesn't have any problem/bugs so he can use it,
other friends have Windows 10 and them have other problems

**Comment by mfreiholz** [comment]
Thanks for your report.
I forgot to add vc_redist.x64.exe to the Installer, but you can download it here: https://www.microsoft.com/en-US/download/details.aspx?id=48145

.. or wait for v0.7, which I will release today.

**Comment by mfreiholz** [comment]
Fixed. You can download the newest version from the homepage: https://mfreiholz.de/ts3video/

**Comment by jedi404** [comment]
check your visual c ++ installs mate. sounds like yer missing one.
