### ISSUE TITLE
Turn-off/pause own video

### ISSUE THREAD

**Issue by mfreiholz** [mfreiholz/ocs#4]
Add option to stop streaming own video.

## Solution 1
Send a "video-pause" event to server and stop streaming video, but do not really turn off the camera. Only show an indicator to the user that the video is now longer send to other participants.

\+ It's very fast to resume the stream
\+ No reset of video decoders required.
\- Could be weird for the user, because the camera light is still on and the user could think that the other users can still see the video.
\- The camera can not be used by another process, in case that this was the intention by the user.

## Solution 2
Send a "video-turned-off" event to server an turn-off the camera completely.

\+ The camera is being shutdown and the user can be absolutely sure that no video is send anymore.
\+ Other processes can access the camera device.
\- Slow reactivation time

**Comment by Kaos1337** [comment]
Sounds something like a "soft pause" and "hard pause" ahah.

**Comment by mfreiholz** [comment]
Fixed with a "hard-pause". It's the best feedback for the user, when the camera light turns off.
